<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>My Blog</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            background-color: #f4f4f4;
            margin: 0;
            padding: 0;
        }
        .container {
            width: 80%;
            margin: auto;
            overflow: hidden;
        }
        header {
            background: #333;
            color: #fff;
            padding: 20px;
            text-align: center;
        }
        .search-box {
            margin: 20px 0;
            text-align: center;
        }
        .search-box input {
            padding: 10px;
            width: 50%;
            font-size: 16px;
        }
        .post {
            background: #fff;
            padding: 20px;
            margin: 20px 0;
            border-radius: 5px;
        }
        .comment-box {
            margin-top: 10px;
        }
        .comment-box input {
            width: 100%;
            padding: 10px;
        }
    </style>
</head>
<body>
    <header>
        <h1>My Blog</h1>
    </header>
    <div class="container">
        <div class="search-box">
            <input type="text" id="search" placeholder="Search blog posts..." onkeyup="searchPosts()">
        </div>
        <div class="post" data-title="Sample Blog Post">
            <h2>Sample Blog Post</h2>
            <p>This is a sample blog post. More content coming soon!</p>
            <div class="comment-box">
                <input type="text" placeholder="Leave a comment...">
            </div>
        </div>
        <div class="post" data-title="Another Blog Post">
            <h2>Another Blog Post</h2>
            <p>This is another example of a blog post.</p>
            <div class="comment-box">
                <input type="text" placeholder="Leave a comment...">
            </div>
        </div>
    </div>

    <script>
        function searchPosts() {
            let input = document.getElementById('search').value.toLowerCase();
            let posts = document.getElementsByClassName('post');
            
            for (let post of posts) {
                let title = post.getAttribute('data-title').toLowerCase();
                if (title.includes(input)) {
                    post.style.display = "block";
                } else {
                    post.style.display = "none";
                }
            }
        }
    </script>
</body>
</html>

